Withdraw
liftlearning/P2Pix-Front-End pull request #41
Opened 2023-02-11 22:49 UTC by brunoedcf

2023-02-13 16:16 UTC, RcleydsonR requested changes
Opa, excelente galera!
Deixei alguns comentários referente a algumas dúvidas minhas que foram surgindo, esse componente foi desenhado inicialmente para ser reutilizado para histórico e gerenciamento de transações, hoje, ele foi redesenhado para abranger esses 2 aspectos em uma só tela. Então, com essas mudanças de design, o código também sofrerá por mudanças, deixei alguns comentários auxiliando as alterações necessárias, essas dúvidas surgiram quando eu estava consertando o script de build (que é necessário estar passando para o deploy ser feito de maneira automática para a vercel). Nesse sentido, peço uma atenção quanto a esse script de build, certifiquem-se de estar passando sempre, e, quando as alterações forem feitas, peço também para efetuar as mudanças no arquivo de teste (que algumas vezes é o responsável pelo build falhar)

2023-02-13 16:16 UTC, RcleydsonR commented on src/components/ListingComponent/ListingComponent.vue
> +  depositList: (Event | ValidDeposit)[];
Opa, acho que o depositList agora só pode ser passado como ValidDeposit, correto? Se esse for o caso, seria interessante colocá-lo para aceitar somente essa tipagem.

2023-02-13 16:16 UTC, RcleydsonR commented on src/components/ListingComponent/ListingComponent.vue
>    walletTransactions: (Event | ValidDeposit)[];
Me parece que o walletTransactions está sendo recebido apenas como a tipagem de Evento, já que o ValidDeposit está sendo passado no parâmetro de depositList. Logo, faz sentido sua tipagem ser única (apenas Event), nesse caso não há necessidade de fazer o cast para Event nas linhas 156 e 175, e também remover o ternário da linha 160.

2023-02-13 16:16 UTC, RcleydsonR commented on src/components/ListingComponent/ListingComponent.vue
> +      <!-- <div class="pt-5" v-if="props.isManageMode">
Pode remover esse código comentado

2023-02-13 16:16 UTC, RcleydsonR commented on src/components/ListingComponent/ListingComponent.vue
>    isManageMode: boolean;
Essa props de isManageMode não faz mais sentido visto que o histórico e gerenciamento de transações estão presentes na mesma tela.

2023-02-13 22:56 UTC, Ronyell requested changes

2023-02-13 22:56 UTC, Ronyell commented on src/components/ListingComponent/ListingComponent.vue
> +    const deposit = props.depositList[0];
Acho que vale a pena colocar aqui que estamos utilizando apenas o primeiro item da lista porque, em principio, teriamos apenas e BRZ

2023-02-14 00:22 UTC, brunoedcf commented on src/components/ListingComponent/ListingComponent.vue
> +    const deposit = props.depositList[0];
Acho válido!

2023-02-15 03:53 UTC, RcleydsonR approved these changes
Excelentes alterações, galera! Mandaram mto, vamoo!

2023-02-15 03:54 UTC, merged