Add icons to redirect to social media on topbar mobile
liftlearning/P2Pix-Front-End pull request #43
Opened 2023-02-15 15:55 UTC by enzoggqs

2023-02-15 15:56 UTC, enzoggqs commented
I still haven't added the behavior of the discord button, because I don't know what the discord of the doiim is

2023-02-15 21:42 UTC, brunoedcf requested changes

2023-02-15 21:42 UTC, brunoedcf commented on src/components/TopBar/TopBar.vue
> -          <div class="w-full flex justify-center pb-20">
Os ícones só estão sendo exibidos no mobile. Precisamos que apareça na versão web também.

2023-02-16 14:30 UTC, enzoggqs commented on src/components/TopBar/TopBar.vue
> -          <div class="w-full flex justify-center pb-20">
Fixed

2023-02-17 22:27 UTC, Ronyell approved these changes

2023-02-17 22:28 UTC, merged